name: 💡 Solicitud de cambio
description: Plantilla para solicitar cambios
title: "[Solicitud de cambio] <titulo>"
labels: []
body:
- type: textarea
  attributes:
    label: Resumen
    description: Redacte un resumen de la solicitud del cambio.
    value: |
      Cambiar...
  validations:
    required: true 
- type: dropdown
  attributes:
    label: Motivo del control de cambio
    options:
      - Cambio del alcance
      - Otros
  validations:
    required: true