name: 💡 Solicitud de cambio
description: Plantilla para solicitar cambios
title: "[Solicitud de cambio] <titulo>"
labels: []
body:
- type: textarea
  attributes:
    label: Resumen
    description: Redacte un resumen de la solicitud del cambio.
    value: |
      Cambiar...
  validations:
    required: true 

- type: dropdown
  attributes:
    label: Motivo del control de cambio
    options:
      - Cambio del alcance
      - Otros
  validations:
    required: true

- type: textarea
  attributes:
    label: Definicion del problema o situacion actual
    description: Detalle la situación actual, incluya estadísticas, cantidad, tiempo, frecuencia, pantallas
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Descripción Detallada del Cambio solicitado
    description: indicar  funcionalidad, aplicativos,  reglas de negocio, reportes
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Descripción Detallada del Cambio solicitado
    description: indicar  funcionalidad, aplicativos,  reglas de negocio, reportes
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Sustento / Beneficios del Cambio
    description: Beneficio cuantitativo y cualitativo, mayores ingresos, menores gastos, mejora de nivel de servicio, etc
    value: |
      Cambiar...
  validations:
    required: true 
