name: 💡 Solicitud de cambio
description: Plantilla para solicitar cambios
title: "[Solicitud de cambio] <titulo>"
labels: []
body:
- type: textarea
  attributes:
    label: Resumen
    description: Redacte un resumen de la solicitud del cambio.
    value: |
      Cambiar...
  validations:
    required: true 

- type: dropdown
  attributes:
    label: Motivo del control de cambio
    options:
      - Cambio del alcance
      - Otros
  validations:
    required: true

- type: textarea
  attributes:
    label: Definicion del problema o situacion actual
    description: Detalle la situación actual, incluya estadísticas, cantidad, tiempo, frecuencia, pantallas
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Descripción Detallada del Cambio solicitado
    description: indicar  funcionalidad, aplicativos,  reglas de negocio, reportes
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Descripción Detallada del Cambio solicitado
    description: indicar  funcionalidad, aplicativos,  reglas de negocio, reportes
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Sustento / Beneficios del Cambio
    description: Beneficio cuantitativo y cualitativo, mayores ingresos, menores gastos, mejora de nivel de servicio, etc
    value: |
      Cambiar...
  validations:
    required: true 

- type: dropdown
    attributes:
      label: Impacto del cambio
      multiple: true
      options:
        - Tiempo
        - Alcance
        - Presupuesto
        - Arquitectura

- type: textarea
  attributes:
    label: Costo asociado
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Horas de esfuerzo
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Fechas impactadas
    value: |
      Cambiar...
  validations:
    required: true

- type: textarea
  attributes:
    label: Impacto en otros requerimientos, proyectos, portafolio u operaciones
    value: |
      Cambiar...
  validations:
    required: true 

- type: textarea
  attributes:
    label: Impacto presupuestal
    value: |
      Cambiar...
  validations:
    required: true 

- type: dropdown
  attributes:
    label: Resolucion
    options:
      - Aprobado
      - Rechazado
  validations:
    required: true

- type: textarea
  attributes:
    label: Motivo del rechazo
    value: |
      Cambiar...
  validations:
    required: true 