---
name:  Plan de Proyecto
about: Plantilla para la creaci贸n de un plan de proyecto detallado
title: "Plan de Proyecto: [Nombre del Proyecto]"
labels: plan-de-proyecto
assignees: ''

# Breve descripci贸n del proyecto.
description: |
  ## Descripci贸n del Proyecto
  <!-- Una breve descripci贸n del proyecto, objetivos y alcance -->

# Metas y Objetivos
objectives: |
  ## Metas y Objetivos
  - Meta 1
  - Objetivo 1
  - Meta 2
  - Objetivo 2

# Alcance del Proyecto
scope: |
  ## Alcance del Proyecto
  <!-- Detallar el alcance del proyecto, incluyendo limitaciones y delimitaciones -->

# Cronograma y Hitos
schedule: |
  ## Cronograma y Hitos
  <!-- Fechas clave, hitos importantes y plazos del proyecto -->

# Recursos y Presupuesto
resources: |
  ## Recursos y Presupuesto
  - Recurso 1: Descripci贸n
  - Recurso 2: Descripci贸n
  - Presupuesto estimado: [Cantidad]

# Riesgos y Mitigaciones
risks: |
  ## Riesgos y Mitigaciones
  - Riesgo 1: Estrategia de mitigaci贸n
  - Riesgo 2: Estrategia de mitigaci贸n

# Roles y Responsabilidades
roles: |
  ## Roles y Responsabilidades
  - Rol 1: Responsabilidad
  - Rol 2: Responsabilidad

# M茅tricas y Evaluaci贸n
metrics: |
  ## M茅tricas y Evaluaci贸n
  <!-- Criterios y m茅todos para evaluar el progreso y 茅xito del proyecto -->

# Comentarios Adicionales
additionalComments: |
  ## Comentarios Adicionales
  <!-- Cualquier otra informaci贸n o comentario relevante -->

---
