name: 💡 Historia de Usuario
description: Plantilla para redactar historia de usuario
title: "[Historia de usuario] <titulo>"
labels: ["user-history"]
body:
- type: textarea
  attributes:
    label: Historia de usuario
    description: Use la sintaxis Como [rol] quiero/puedo/necesito [funcion o accion] para [resultado o beneficio esperado].
    value: |
      Como [rol] quiero/puedo/necesito [funcion o accion] para [resultado o beneficio esperado].
  validations:
    required: true 
- type: textarea
  attributes:
    label: Pre condiciones
    description: Describe las pre condiciones de ser necesario
    value: |
      Ej. el usuario esta autenticado.
  validations:
    required: true 
- type: textarea
  attributes:
    label: Criterios de aceptacion
    description: Describe los escenarios
    value: |
      Escenario #
      Given
      When
      Then

      Escenario #
      Given
      When
      Then

      Escenario #
      Given
      When
      Then
  validations:
    required: true 
- type: dropdown
  attributes:
    label: Prioridad
    description: Prioridad de la tarea
    options: 
      - Alto
      - Medio
      - Bajo
  validations:
      required: true
