name: Historia de Usuario
description: Plantilla para crear historias de usuario, criterios de aceptacion y tareas
title: "[Historia de Usuario]: "
labels: ["user-history"]
projects: []
assignees: []
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
