name: Historia de Usuario
description: Plantilla para crear historias de usuario, criterios de aceptacion y tareas
title: "[Historia de Usuario]: "
labels: ["user-history"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Gracias por llenar el reporte
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
